{
 "title": "SenseHAT",
 "description": "Dashboard for the Raspberry Pi",
 "tags": [
  "SenseHAT",
  "Raspberry Pi"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "1s,5s,10s,15s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "location", "query": "SELECT location FROM sense_hat" },
   { "name": "room", "query": "SELECT room FROM sense_hat" }
  ]
 },
 "panels": [
  {
   "title": "Temperature:",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sense_hat",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sense_hat",
     "query": "SELECT last(\"temperaturevalue\") FROM \"autogen\".\"sensehat\" WHERE (\"runNum\" = '201803031829') AND $timeFilter GROUP BY time(10s) fill(null)",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Humidity:",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 7 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sensehat",
     "select": [
      [
       { "params": [ "humidityvalue" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "runNum", "operator": "=", "value": "201803031829" }
     ]
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sensehat",
     "select": [
      [
       { "params": [ "humidityvalue" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " " ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "runNum", "operator": "=", "value": "201803031829" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sensehat",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "runNum", "operator": "=", "value": "201803031824" }
     ]
    }
   ]
  },
  {
   "title": "Pressure:",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 14 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sensehat",
     "select": [
      [
       { "params": [ "pressurevalue" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "runNum", "operator": "=", "value": "201803031829" }
     ]
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "graph",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sensehat",
     "select": [
      [
       { "params": [ "pressurevalue" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " " ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "runNum", "operator": "=", "value": "201803031829" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sensehat",
     "select": [
      [
       { "params": [ "pressurevalue" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " " ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "runNum", "operator": "=", "value": "201803031818" }
     ]
    }
   ]
  }
 ]
}